---
# Sub playbook to install all security components needed.

- name: SSL Phase 1 (Prepare Servers)
  hosts: all
  roles:
    - { role: ssl-phase-1, when: SECURITY_ENABLED == true }

- name: SSL Phase 2 (Sign CSRs)
  hosts: kdc_server
  roles:
    - { role: ssl-phase-2, when: SECURITY_ENABLED == true }

- name: SSL Phase 3 (Install CSRs and Truststores)
  hosts: all
  roles:
    - { role: ssl-phase-3, when: SECURITY_ENABLED == true }

