---
# Sub playbook to install all monitoring components needed.

- name: Install monitoring collection daemons
  hosts: monitoring_collection

  roles:
    - monitoring-collection

- name: Install monitoring aggregation daemons
  hosts: monitoring_aggregation

  roles:
    - monitoring-aggregation

- name: Install monitoring frontend
  hosts: monitoring_frontend

  roles:
    - monitoring-frontend
